project:
  type: website

website:
  title: "Glynn Boltman, Comms Website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/glynnboltman/comm3180_S26_Blog
format:
  html:
    theme: flatly
    css: styles.css

execute:
  freeze: auto


